### ISSUE TITLE
need apple certificate

### ISSUE THREAD

**Issue by Momonosmoke** [sudo903/apple-code-gen#1]
Uncaught Exception:
Error: Could not get code signature for running application
at initUpdater (/Applications/apple-code-gen.app/Contents/Resources/app.asar/node_modules/update-electron-app/index.js:54:15)
at updater (/Applications/apple-code-gen.app/Contents/Resources/app.asar/node_modules/update-electron-app/index.js:32:7)
at App.<anonymous> (evalmachine.<anonymous>:1:1323)
at App.emit (events.js:315:20)

**Comment by sudo903** [comment]
Use the darwin ZIP from latest release

**Comment by Momonosmoke** [comment]
> Use the darwin ZIP from latest release

using yarn is a good idea
